@ECHO OFF
REM COMENTARIO
ECHO HOLA
::COMENTARIO
ECHO COMO
CALL "C:\Users\Jersson-PHP\Desktop\ARCHIVOS POR LOTES\BAT\05.BAT"
ECHO OK
REM ARCHIVOS BATCH O POR LOTES
IF ROJO==ROJO ECHO EL COLOR ROJO
IF ROJO==VERDE ECHO EL COLOR VERDE 
IF %1==ROJO ECHO EL COLOR ES ROJO 
REM >07.BAT ROJO DEL ARCHIVO
SET /A VARIABLEERROR=0
IF ERRORLEVEL 0 ECHO ERROR
REM SI ES DIFERENTE DE 0 NO ES ERROR 
REM PATH C:\;C:\DOS;C:\WINDOWS

REM SET TEMP=C:\TEMP
REM DOSKEY
REM --------- EJECUTAR HASTA QUE INGRESE BANNER.EXE -----------
REM @ECHO OFF
REM DATE
REM TIME
REM SET TEMP=C:\TEMP
REM :BUCLE
REM IF EXIST A:\BANNER.EXE GOTO BIEN
REM ECHO Colocar el Disquete con el programa BANNER
REM PAUSE
REM GOTO BUCLE
REM :BIEN
REM A:\BANNER


PROMPT $T 
REM MUESTRA LA HORA ACTUAL
REM COMANDOS EJECUTABLES EN PATH












