@ECHO OFF
TITLE OPERACIONES BASICAS
ECHO INGRESE EL PRIMER NUMERO
SET/P NUMA=PRIMER CARACTER...........
ECHO INGRESE EL SEGUNDO NUMERO
SET/P NUMB=
SET/A SUMA=(%NUMA%+%NUMB%)
ECHO.
ECHO %SUMA%
ECHO.
PAUSE
EXIT
:: set/p suma1=Primer caracter:...........